2024-11-16 23:26:04,278 INFO    MainThread:854747 [wandb_setup.py:_flush():79] Current SDK version is 0.18.6
2024-11-16 23:26:04,278 INFO    MainThread:854747 [wandb_setup.py:_flush():79] Configure stats pid to 854747
2024-11-16 23:26:04,279 INFO    MainThread:854747 [wandb_setup.py:_flush():79] Loading settings from /home/al2644/.config/wandb/settings
2024-11-16 23:26:04,279 INFO    MainThread:854747 [wandb_setup.py:_flush():79] Loading settings from /home/al2644/research/codebase/knowledge_update/continued_pretraining/wandb/settings
2024-11-16 23:26:04,279 INFO    MainThread:854747 [wandb_setup.py:_flush():79] Loading settings from environment variables: {'api_key': '***REDACTED***', 'project': 'knowledge-update-continued-pretraining'}
2024-11-16 23:26:04,279 INFO    MainThread:854747 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-11-16 23:26:04,279 INFO    MainThread:854747 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program_abspath': '/home/al2644/research/codebase/knowledge_update/continued_pretraining/train.py', 'program': '/home/al2644/research/codebase/knowledge_update/continued_pretraining/train.py'}
2024-11-16 23:26:04,279 INFO    MainThread:854747 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-16 23:26:04,279 INFO    MainThread:854747 [wandb_init.py:_log_setup():533] Logging user logs to /home/al2644/research/codebase/knowledge_update/continued_pretraining/wandb/run-20241116_232604-53ddtbpi/logs/debug.log
2024-11-16 23:26:04,279 INFO    MainThread:854747 [wandb_init.py:_log_setup():534] Logging internal logs to /home/al2644/research/codebase/knowledge_update/continued_pretraining/wandb/run-20241116_232604-53ddtbpi/logs/debug-internal.log
2024-11-16 23:26:04,279 INFO    MainThread:854747 [wandb_init.py:init():619] calling init triggers
2024-11-16 23:26:04,279 INFO    MainThread:854747 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {}
2024-11-16 23:26:04,279 INFO    MainThread:854747 [wandb_init.py:init():669] starting backend
2024-11-16 23:26:04,279 INFO    MainThread:854747 [wandb_init.py:init():673] sending inform_init request
2024-11-16 23:26:04,281 INFO    MainThread:854747 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-11-16 23:26:04,282 INFO    MainThread:854747 [wandb_init.py:init():686] backend started and connected
2024-11-16 23:26:04,290 INFO    MainThread:854747 [wandb_init.py:init():781] updated telemetry
2024-11-16 23:26:04,293 INFO    MainThread:854747 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2024-11-16 23:26:05,099 ERROR   MainThread:854747 [wandb_init.py:init():841] encountered error: failed to upsert bucket: returned error 401 Unauthorized: {"errors":[{"message":"user is not logged in","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-11-16 23:26:05,099 ERROR   MainThread:854747 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "/home/al2644/anaconda3/envs/nlp/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/al2644/anaconda3/envs/nlp/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 847, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 401 Unauthorized: {"errors":[{"message":"user is not logged in","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-11-16 23:26:05,188 WARNING MsgRouterThr:854747 [router.py:message_loop():75] message_loop has been closed
